### ISSUE TITLE
Problem with a link 

### ISSUE THREAD

**Issue by dandusty** [akhater/Lupin#12]
Tried to send this link to Lupin - https://editorial.rottentomatoes.com/article/new-on-netflix-in-march-2021/ and Lupin errored. 

No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
    return self.callback(update, context)
  File "main.py", line 37, in addEntry
    updateJournal(update.message.text)
  File "/home/ec2-user/Lupin/git.py", line 40, in updateJournal
    entry = buildJournalEntry(entry, ignoreURL)
  File "/home/ec2-user/Lupin/git.py", line 96, in buildJournalEntry
    journalEntry = journalEntry.replace(journalEntryURL, '#' + config.BookmarkTag + ' [' + title + '](' + journalEntryURL + ')')
TypeError: can only concatenate str (not "Exception") to str

**Comment by akhater** [comment]
the guys decided to include "<<" in the title 🤣 messed up my regex

**Comment by akhater** [comment]
fixed with latest commit, requires BeautifulSoup4 to be installed
