### ISSUE TITLE
github.GithubException.UnknownObjectException

### ISSUE THREAD

**Issue by klchen0112** [akhater/Lupin#17]
I'm trying to install Lupin for the first time and get the following error:
```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from git import updateJournal, updateAsset, Git2Json, updateCalendarsFile, encryptGraph, decryptGraph, getAllThemes, switchTheme #, updateFlashCards
  File "/root/Lupin/git.py", line 20, in <module>
    repo = g.get_repo(GitHubFullRepo)
  File "/usr/local/lib/python3.6/site-packages/github/MainClass.py", line 346, in get_repo
    "GET", f"{url_base}{full_name_or_id}"
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

**Comment by akhater** [comment]
Hi, this error is related to the GitHub API, more often than not it is caused by a wrong API key in the config.ini file...

can you please double check that ?

**Comment by klchen0112** [comment]
> Hi, this error is related to the GitHub API, more often than not it is caused by a wrong API key in the config.ini file...
> 
> can you please double check that ?

Thank you. I find thay my GitHubUser is wrong.
